#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ps/functions"

list-main-cmd() {
  declare desc="list all dokku apps"
  local cmd="list"
  [[ "$1" == "$cmd" ]] && shift 1
  local DOKKU_APP_RUNNING_CONTAINER_IDS INSTANCES
  echo "Image        Name"

  for app in $(dokku_apps); do
    DOKKU_APP_RUNNING_CONTAINER_IDS=$(get_app_running_container_ids "$app")
    for i in $DOKKU_APP_RUNNING_CONTAINER_IDS; do
      echo "${i:0:12}" $(docker inspect "$i" | grep Image | grep -v sha256 | head -n1 | cut -d\" -f4 || true )
    done
  done

}

list-main-cmd "$@"
