#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

list-main-cmd() {
  declare desc="list all dokku apps"
  local cmd="list"
  [[ "$1" == "$cmd" ]] && shift 1
  local INSTANCES
  INSTANCES=$(docker ps -q | cut -d\  -f1 | tr '\n' ' ')
  echo "Image        Name"

  OLDIFS="$IFS"
  IFS=" "
  SUBCOMMAND="$1"

  for i in $INSTANCES; do
    echo "$i" $(docker inspect "$i" | grep Image | head -n1 | cut -d\" -f4 || true )
  done
}

list-main-cmd "$@"
